name: docker build
on: push

jobs:
    build:
        runs-on: ubuntu-22.04
        strategy:
            fail-fast: false
            matrix:
                include:
                    - image: debian:stable

        container:
            image: ${{ matrix.image }}

        steps:
            - name: Checkout main repository
              uses: actions/checkout@v3
            # - name: Checkout developer-meta-files
            #   uses: actions/checkout@v3
            #   with:
            #       repository: Kicksecure/developer-meta-files
            #       path: developer-meta-files
            - name: System Basic Packages
              run: |
                  apt-get update
                  apt-get install --yes --no-install-recommends adduser shellcheck libxml2-utils wixl fpc lazarus git ca-certificates libfile-mimeinfo-perl
            - name: Install Packages from Debian trixie
              run: |
                  echo 'deb https://deb.debian.org/debian trixie main' | tee /etc/apt/sources.list.d/trixie.list
                  apt-get update
                  apt-get install --yes --no-install-recommends fp-units-win-base fp-units-win-rtl fp-units-win-fcl fp-units-win-misc
            - name: System information
              run: |
                  whoami
                  cat /etc/os-release
                  uname -a
                  echo "${PATH}"
            - name: Create regular (non-root) user
              run: adduser --comment "" --disabled-password user
            - name: Linux user file permissions fix
              run: chown --recursive user:user /__w/Whonix-Starter
            # - name: ppcross_install
            #   run: ./developer-meta-files/usr/bin/ppcross_install all
            - name: Build Starter
              run: su -s /bin/bash user -- ./build_on_linux_for_win64
            - name: ShellCheck
              run: shellcheck ./build_on_linux_for_win64

# vim: sw=4
